-- Contenido del glosario: 189 palabras del material actual, con su traduccion.
--
-- Seleccion: todos los phrasal verbs (en su forma completa, verbo + particula)
-- y conectores que detecta el analizador, mas el vocabulario de dificultad 3-5
-- cuya forma base no figure en las listas de palabras comunes.
--
-- Ese ultimo filtro evita tarjetas inutiles como "working" o "started": salian
-- marcadas solo porque la forma conjugada no esta en las listas, aunque el
-- verbo sea de los mas comunes. Ademas se descarto a mano una veintena
-- demasiado facil para merecer tarjeta (ready, coffee, worst...).
--
-- ON CONFLICT DO NOTHING: idempotente, y no pisa nada que corrijas a mano.

INSERT INTO glossary (word, translation, tag, note) VALUES ('absolute', 'absoluto, total', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('absolutely', 'por supuesto, totalmente', 'connector', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('accomplishing', 'logrando, consiguiendo', 'vocab', 'de *accomplish*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('account', 'cuenta (bancaria, de usuario)', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('acquired', 'adquirida, comprada (una empresa)', 'vocab', 'de *acquire*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('actually', 'en realidad, de hecho', 'connector', 'OJO: no significa "actualmente"') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('afterwards', 'después, más tarde', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('agenda', 'orden del día, temario', 'vocab', 'OJO: la agenda de citas es *diary* o *planner*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('although', 'aunque, si bien', 'connector', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('annual', 'anual', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('anyway', 'en fin, de todos modos', 'connector', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('apparently', 'al parecer, por lo visto', 'connector', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('athlete', 'atleta, deportista', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('athletic', 'atlético, deportivo', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('audacity', 'descaro, osadía', 'vocab', 'have the audacity to = tener el descaro de') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('average', 'promedio, media', 'vocab', 'on average = en promedio') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('back-up', 'coros (en música); refuerzo, respaldo', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('background', 'trayectoria, formación; segundo plano', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('backing down', 'echarse para atrás, rajarse', 'phrasal_verb', 'de *back down*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('bathroom', 'baño', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('beauty', 'belleza', 'vocab', 'beauty products = productos de belleza') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('biggest', 'el más grande', 'vocab', 'superlativo de *big*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('biking', 'ciclismo, montar en bici', 'vocab', 'mountain biking = ciclismo de montaña') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('blocking', 'bloqueante, que traba el avance', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('bluegrass', 'bluegrass (género musical de EE. UU.)', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('bother', 'molestarse en hacer algo', 'vocab', 'I won''t bother = no me voy a molestar') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('brings in', 'atrae, trae (clientes, dinero)', 'phrasal_verb', 'de *bring in*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('broken up', 'desarmado, disuelto, separado', 'phrasal_verb', 'de *break up*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('brought up', 'criado; sacar un tema', 'phrasal_verb', 'de *bring up*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('categorize', 'categorizar, clasificar', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('certainly', 'sin duda, ciertamente', 'connector', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('chalet', 'cabaña, chalet (de montaña)', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('check in', 'registrarse (hotel, vuelo); dar señales de vida', 'phrasal_verb', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('clock', 'marcar entrada o salida', 'vocab', 'clock in = marcar entrada') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('combining', 'combinando, que reúne', 'vocab', 'de *combine*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('come up', 'surgir, presentarse (algo inesperado)', 'phrasal_verb', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('comes around', 'pasa por ahí, se da una vuelta', 'phrasal_verb', 'de *come around*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('coming along', 'venir también, acompañar; ir progresando', 'phrasal_verb', 'de *come along*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('coming in', 'entrar, pasar adelante', 'phrasal_verb', 'de *come in*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('communicated', 'comunicado, transmitido', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('comprehensive', 'exhaustivo, completo', 'vocab', 'OJO: no significa "comprensivo"') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('consisted', 'estaba conformado por', 'vocab', 'consist of = constar de') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('cooked', 'cociné, cocinado', 'vocab', 'de *cook*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('cramps', 'calambres', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('currently', 'actualmente, en este momento', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('cut down', 'reducir, bajarle a algo', 'phrasal_verb', 'cut down on coffee = bajarle al café') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('deadlines', 'plazos, fechas límite', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('deal with', 'lidiar con, manejar, encargarse de', 'phrasal_verb', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('debut', 'debut, estreno', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('decent-looking', 'de buen ver, bien parecido', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('dishwashing', 'lavado de platos', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('doubt', 'dudar; duda', 'vocab', 'I doubt it = lo dudo') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('dreamt', 'soñé, soñado', 'vocab', 'pasado irregular de *dream*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('drums', 'batería (instrumento)', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('e-mail', 'correo electrónico', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('engineering', 'ingeniería', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('enriching', 'enriquecedora', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('entertainment', 'entretenimiento, espectáculo', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('excellent', 'excelente', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('excited', 'emocionado, entusiasmado', 'vocab', 'excited about = emocionado por') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('familiar', 'familiarizado, que conoce', 'vocab', 'familiar with = conocer algo') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('fault', 'culpa', 'vocab', 'my fault = culpa mía') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('features', 'funciones, características', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('fifteen', 'quince', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('figure out', 'descifrar, darse cuenta, resolver', 'phrasal_verb', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('gaining', 'ganando, subiendo (de peso)', 'vocab', 'de *gain*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('genuinely', 'realmente, de verdad', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('get rid', 'deshacerse de, quitarse de encima', 'phrasal_verb', 'siempre con *of*: get rid of it') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('go out', 'salir (de casa, o con alguien)', 'phrasal_verb', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('got back', 'volvió; me respondió', 'phrasal_verb', 'de *get back*: get back to me = responderme') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('gradually', 'poco a poco, gradualmente', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('graduating', 'graduándome, terminando la carrera', 'vocab', 'de *graduate*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('grew up', 'creció, se crió', 'phrasal_verb', 'de *grow up*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('guitar', 'guitarra', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('headache', 'dolor de cabeza', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('hilarious', 'divertidísimo, muy gracioso', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('honestly', 'sinceramente, la verdad', 'connector', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('honoured', 'galardonado, homenajeado', 'vocab', 'grafía británica de *honored*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('however', 'sin embargo, no obstante', 'connector', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('humorous', 'con humor, cómico', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('impress', 'impresionar, causar buena impresión', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('individuality', 'individualidad', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('influences', 'influencias, referentes', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('input', 'aportar, aportación', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('intimately', 'de cerca, íntimamente', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('journey', 'viaje, trayecto, etapa', 'vocab', 'más largo o vital que *trip*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('judge', 'juzgar; juez', 'vocab', 'judge a book by its cover = juzgar por las apariencias') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('kicking', 'pateando', 'vocab', 'de *kick*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('learnt', 'aprendí, aprendido', 'vocab', 'grafía británica; en EE. UU. *learned*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('legislative', 'legislativo', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('loafing around', 'haraganeando, vagueando', 'phrasal_verb', 'de *loaf around*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('logistics', 'logística', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('look into', 'investigar, averiguar, mirar el tema', 'phrasal_verb', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('looking back', 'mirando atrás, en retrospectiva', 'phrasal_verb', 'de *look back*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('looking for', 'buscando', 'phrasal_verb', 'de *look for*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('makeup', 'maquillaje', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('marathon', 'maratón', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('meantime', 'mientras tanto', 'vocab', 'in the meantime = entre tanto') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('messenger', 'mensajero; mensajería', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('motorcycle', 'motocicleta', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('mountain', 'montaña', 'vocab', 'mountain biking = ciclismo de montaña') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('mountains', 'montañas', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('move on', 'seguir adelante, pasar a otra cosa', 'phrasal_verb', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('moved in', 'se mudó (a vivir)', 'phrasal_verb', 'de *move in*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('napkin', 'servilleta', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('necessarily', 'necesariamente', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('negotiated', 'negociado', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('neighborhood', 'vecindario, barrio', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('nervous', 'nervioso', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('nevertheless', 'aun así, sin embargo', 'connector', 'más formal que *however*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('new-age', 'new age, de la nueva era', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('novelty', 'novedad', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('occasional', 'ocasional, esporádico', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('otherwise', 'si no, de lo contrario', 'connector', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('outbound', 'saliente (llamadas, ventas)', 'vocab', 'lo contrario de *inbound*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('packed', 'lleno, a reventar; empacado', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('panic', 'pánico; entrar en pánico', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('paracetamol', 'paracetamol, acetaminofén', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('passion', 'pasión', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('pissed off', 'furioso, encabronado', 'phrasal_verb', 'informal, algo vulgar') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('polish', 'esmalte; pulir', 'vocab', 'nail polish = esmalte de uñas') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('politics', 'política (la actividad)', 'vocab', 'OJO: *policy* es una política concreta') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('popularity', 'popularidad', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('postpone', 'aplazar, posponer', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('prejudge', 'prejuzgar', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('previous', 'anterior, previo', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('printed out', 'imprimió', 'phrasal_verb', 'de *print out*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('profession', 'profesión', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('promises', 'promesas (también: talentos jóvenes)', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('properly', 'bien, como es debido', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('proposal', 'propuesta', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('push back', 'aplazar; plantarse, oponerse', 'phrasal_verb', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('putting in', 'metiendo, invirtiendo (esfuerzo, horas)', 'phrasal_verb', 'de *put in*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('raining', 'lloviendo', 'vocab', 'raining cats and dogs = lloviendo a cántaros') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('reaction', 'reacción', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('recommend', 'recomendar', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('regarding', 'relacionado con, en cuanto a', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('residents', 'residentes, habitantes', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('rhythm', 'ritmo', 'vocab', 'rhythm guitar = guitarra rítmica') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('riding', 'montando (bici, moto, caballo)', 'vocab', 'de *ride*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('roommate', 'compañero de cuarto o de piso', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('saint', 'santo', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('scheduled', 'programado, agendado', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('scope', 'alcance (de un proyecto)', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('separate', 'separar, dividir; separado', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('session', 'sesión', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('short-staffed', 'con poco personal, cortos de gente', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('sit around', 'estar sentado sin hacer nada', 'phrasal_verb', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('soccer', 'fútbol', 'vocab', 'en EE. UU.; en el Reino Unido *football*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('software', 'software', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('somewhere', 'en algún lugar', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('sounded like', 'sonaba a, parecía', 'phrasal_verb', 'de *sound like*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('sphere', 'ámbito, esfera', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('spotlight', 'reflector; el centro de atención', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('squad', 'equipo, plantilla, convocatoria', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('strengths', 'fortalezas, puntos fuertes', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('stumbled', 'se tambaleó, tropezó', 'vocab', 'de *stumble*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('surname', 'apellido', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('synonym', 'sinónimo', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('take on', 'asumir, hacerse cargo de', 'phrasal_verb', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('talking about', 'hablando de', 'phrasal_verb', 'de *talk about*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('teamwork', 'trabajo en equipo', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('technical', 'técnico', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('tennis', 'tenis', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('terrible', 'terrible, espantoso', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('thirty-second', 'trigésimo segundo', 'vocab', 'ordinal, no "treinta y dos"') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('tight', 'ajustado, apretado', 'vocab', 'tight deadlines = plazos ajustados') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('totally', 'totalmente, del todo', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('touch', 'contacto', 'vocab', 'lose touch with = perder el contacto con') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('turned out', 'resultó (que)', 'phrasal_verb', 'de *turn out*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('turtle', 'tortuga', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('twisted', 'retorcido, enrevesado', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('uncles', 'tíos', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('unfavourably', 'desfavorablemente', 'vocab', 'grafía británica de *unfavorably*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('unless', 'a menos que, salvo que', 'connector', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('unreliable', 'poco confiable, poco fiable', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('upper', 'superior, alto', 'vocab', 'upper class = clase alta') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('upside', 'al revés, patas arriba', 'vocab', 'upside down = patas arriba') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('village', 'pueblo, aldea', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('vocals', 'voz, la parte cantada', 'vocab', 'sing vocals = ser el vocalista') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('voted', 'voté, votado', 'vocab', 'vote for = votar por') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('wake up', 'despertarse', 'phrasal_verb', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('weaknesses', 'debilidades, puntos débiles', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('wealthy', 'adinerado, rico', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('wears off', 'se le pasa el efecto', 'phrasal_verb', 'de *wear off*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('wedding', 'boda, matrimonio', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('win-win', 'en la que todos ganan', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('working on', 'trabajando en', 'phrasal_verb', 'de *work on*') ON CONFLICT (word) DO NOTHING;
INSERT INTO glossary (word, translation, tag, note) VALUES ('worthless', 'inútil, sin valor', 'vocab', NULL) ON CONFLICT (word) DO NOTHING;

DO $$
DECLARE n INTEGER;
BEGIN
    SELECT COUNT(*) INTO n FROM glossary;
    RAISE NOTICE 'glosario: % palabras', n;
END $$;
